return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      local config = require('nvim-treesitter.configs')
      config.setup({
        ensure_installed = {
          "asm",
          "bash", 
          "c", 
          "clojure", 
          "cmake", 
          "cpp", 
          "css", 
          "csv",
          "cuda",
          "diff", 
          "dockerfile", 
          "fish", 
          "git_config",
          "git_rebase", 
          "gitattributes",
          "gitcommit", 
          "gitignore", 
          "go",
          "graphql",
          "gomod",
          "groovy",
          "haskell",
          "helm",
          "html",
          "http",
          "hyprlang",
          "java",
          "javadoc",
          "javascript",
          "jq",
          "json",
          "json5",
          "kotlin",
          "llvm",
          "lua",
          "make",
          "markdown",
          "ocaml",
          "properties",
          "proto",
          "python",
          "regex",
          "ruby",
          "rust",
          "scala",
          "sql",
          "swift",
          "terraform",
          "tmux",
          "toml",
          "tsv",
          "tsx",
          "typescript",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
          "zig",
        },
        highlight = {
          enable = true,
        },
        indent = {
          enable = true,
        },
      })
    end
  },
}
