return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    local config = require("nvim-treesitter.configs")
    config.setup({
      auto_install = true,
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "clojure",
        "cmake",
        "cpp",
        "css",
        "dart",
        "diff",
        "erlang",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "groovy",
        "haskell",
        "html",
        "http",
        "java",
        "javadoc",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "kotlin",
        "lua",
        "make",
        "nix",
        "objc",
        "proto",
        "python",
        "regex",
        "rust",
        "scala",
        "sql",
        "swift",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
      },
      highlight = { enable = true },
      indent = { enable = false },
    })
  end
}
